DROP TABLE IF EXISTS SQOOP_SESSIONS;
DROP TABLE IF EXISTS SQOOP_ROOT;
CREATE TABLE SQOOP_ROOT (
	VERSION INTEGER,
	PROPNAME VARCHAR(128) NOT NULL,
	PROPVAL VARCHAR(256)
);
CREATE INDEX IX_SQOOP_ROOT ON SQOOP_ROOT (VERSION, PROPNAME);
CREATE TABLE SQOOP_SESSIONS (
	JOB_NAME VARCHAR(64) NOT NULL,
	PROPNAME VARCHAR(128) NOT NULL,
	PROPVAL VARCHAR(1024),
	PROPCLASS VARCHAR(32) NOT NULL
);
CREATE INDEX IX_SQOOP_SESSIONS ON SQOOP_SESSIONS (JOB_NAME, PROPNAME, PROPCLASS);
