DROP TABLE IF EXISTS FOO;
DROP TABLE IF EXISTS BAR;
CREATE TABLE FOO (ID smallint NOT NULL, ARTIST varchar(255), TITLE varchar(255), PRIMARY KEY (ID));
CREATE TABLE BAR (ID smallint NOT NULL, ARTIST varchar(255), TITLE varchar(255), PRIMARY KEY (ID));