INSERT INTO FOO VALUES(1, 'ONE', 'ONEVALUE');
INSERT INTO FOO VALUES(2, 'TWO', 'TWOVALUE');
INSERT INTO FOO VALUES(3, 'THREE', 'THREEVALUE');
INSERT INTO FOO VALUES(4, 'FOUR', 'FOURVALUE');
INSERT INTO FOO VALUES(5, 'FIVE', 'FIVEVALUE');
INSERT INTO FOO VALUES(6, 'SIX', 'SIXVALUE');
